CREATE ROLE SMART_LIVING_USER;

GRANT SELECT,INSERT,UPDATE,DELETE on "XDB"."CATEGORY" to SMART_LIVING_USER;

GRANT CREATE ANY,DELETE,DROP,EXECUTE,INDEX,INSERT,SELECT ON SCHEMA XDB TO XAVIERAD1 WITH GRANT OPTION;